### PR TITLE
cluster id, update fleet dashboard, fix logging node selectors

### PR DESCRIPTION
**Pull request by pb82**
cluster id, update fleet dashboard, fix logging node selectors

### CODE REVIEW

**Review by damienomurchu — APPROVED** [review]
lgtm

**Comment by Rajagopalan-Ranganathan** [comment]
ClusterID: appears in the global monitoring metrics:

**Comment by Rajagopalan-Ranganathan** [comment]
Global fleet management dashboard: 
image

**Comment by Rajagopalan-Ranganathan** [comment]
clusterID present in Global thanos: 
image

**Comment by Rajagopalan-Ranganathan** [comment]
/approve
everything looks good to be merged.

**Pull request merged**
