### PR TITLE
Fleet dashboard

### PR DESCRIPTION
**Pull request by pb82**
Adds a fleet dashboard to the global monitoring stack that shows:

* Kafka Provision success rate
* Strimzi operator version breakdown
* OpenShift version breakdown
* URLs to Strimzi clusters
* Active alerts on strimzi clusters

fleet

### CODE REVIEW

**Comment by david-martin** [comment]
@pb82 This looks great.
Would it be possible to add a singlestat count of how many kafka clusters there are and how many OSD clusters there are that have at least 1 Kafka on it?

Also, a separate followup issue to show the total number of Kafka CRs across all clusters (seems like this will require some new metric maybe?)

**Comment by pb82** [comment]
@david-martin yes, that's possible, i'm going to add those.

**Comment by pb82** [comment]
@david-martin added the requested panels and updated the screenshot

**Comment by Rajagopalan-Ranganathan** [comment]
Verified in an OSD cluster that the fleet management dashboard works. Kafka metrics are present in the Grafana.

**Comment by Rajagopalan-Ranganathan** [comment]
The updated changes are verified too.  @pb82 what  are the alerts firing? I have a "kubejobcompletion" alert at warning level.

**Comment by pb82** [comment]
@Rajagopalan-Ranganathan I haven't looked into the details of the Alerts, it only shows all alerts that are firing on clusters containing Kafka installations

**Review by david-martin — APPROVED** [review]
@pb82 Nice

**Comment by david-martin** [comment]
Happy to merge once @Rajagopalan-Ranganathan and @damienomurchu have approved

**Pull request merged**
